# Generated by Django 5.1.7 on 2025-05-07 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeCaveBackApp', '0003_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_ua', models.CharField(max_length=50)),
                ('date_us', models.CharField(max_length=50)),
                ('created_at_ua', models.CharField(max_length=50)),
                ('created_at_us', models.CharField(max_length=50)),
                ('preview', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
                ('hashtags', models.JSONField(default=list)),
                ('likes', models.IntegerField(default=0)),
                ('timecodes', models.JSONField(default=list)),
                ('materials', models.JSONField(default=list)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
