# Generated by Django 5.1.7 on 2025-05-11 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeCaveBackApp', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at_ua',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_at_us',
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
