# Generated by Django 5.1.7 on 2025-05-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeCaveBackApp', '0006_remove_video_created_at_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
