# Generated by Django 5.2 on 2025-05-23 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeCaveBackApp', '0008_video_min_subscription_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='preview'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
